### ISSUE TITLE
How to make 24 game

### ISSUE THREAD

**Issue by kim8mumu** [ssac-debbu/game_24#1]
## 목표

팀 프로젝트로 24game 구현

## 요구사항

최종 결과가 24가 되도록 4개의 정수를 조작하는 방법을 찾아낸다.

## Tasks

- [x] 카드는 1부터 9까지의 숫자가 있음.
- [x] 카드는 네 장 지급받는다.
- [x] 카드의 숫자로 사칙연산을 활용해 숫자 24를 만든다.
- [x] 24가 만들어지면 '완료!'를 출력한다.

## References

https://h2g2.com/edited_entry/A933121

**Comment by 2JISUN** [comment]
wow .. 100년동안 멈춰있던 제 심장이 뛰기 시작했읍니다.. 감사합니다..
